// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuViNLwgDeuyUesj7i0Zba00_hLRHMnZY',
    appId: '1:1094252368136:web:f135382d47dd4d04435cbd',
    messagingSenderId: '1094252368136',
    projectId: 'gemini-chatbot-ca8d1',
    authDomain: 'gemini-chatbot-ca8d1.firebaseapp.com',
    storageBucket: 'gemini-chatbot-ca8d1.appspot.com',
    measurementId: 'G-8ZY6ZMS97P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7LMPSVlKhoPYvog6actXLTSoQB67TLQs',
    appId: '1:1094252368136:android:0f8f9bee25f55d70435cbd',
    messagingSenderId: '1094252368136',
    projectId: 'gemini-chatbot-ca8d1',
    storageBucket: 'gemini-chatbot-ca8d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9ME8MtNkYIXzBNUmrYQWFoYWJlHfgm8',
    appId: '1:1094252368136:ios:720231d402a13e27435cbd',
    messagingSenderId: '1094252368136',
    projectId: 'gemini-chatbot-ca8d1',
    storageBucket: 'gemini-chatbot-ca8d1.appspot.com',
    iosBundleId: 'com.example.geminiChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ9ME8MtNkYIXzBNUmrYQWFoYWJlHfgm8',
    appId: '1:1094252368136:ios:b73d9757729fc9b1435cbd',
    messagingSenderId: '1094252368136',
    projectId: 'gemini-chatbot-ca8d1',
    storageBucket: 'gemini-chatbot-ca8d1.appspot.com',
    iosBundleId: 'com.example.geminiChatbot.RunnerTests',
  );
}
